name = "voting-app"
main = "src/worker.js"
compatibility_date = "2025-02-22"
workers_dev = true

[[kv_namespaces]]
binding = "poll_kv"
id = "162a8e597ebc492d95c54ebaf003af9b"

[observability]
enabled = true
head_sampling_rate = 1